### ISSUE TITLE
Comparison with similar packages

### ISSUE THREAD

**Issue by dandv** [zimme/meteor-collection-behaviours#12]
I see at the end of the README that this package was inspired by @Sewdn's collection-behaviors. Users who are trying to choose the most appropriate package for their app would love to learn more details about the differences.

@jagi's [Astronomy also has behaviors](https://github.com/jagi/meteor-astronomy/wiki/Behaviors).

How does this package compare with the other two that existed before it?

**Comment by zimme** [comment]
As @jagi mentions for some of the other collection packages, this package focuses on only on one thing, attaching behaviours to collections.

Differently from @sewdn's package, this package is only a `base` package which allows you to `define`, `attach` and `configure` a behaviour. So you can either use this package by itself in your app and define your own behaviours or you can use one of the pre-made behaviour packages like `zimme:collection-timestampable` or `zimme:collection-softremovable`. This package also provides configuration for behaviours on a `global` level i.e. overriding behaviour defaults for all collections using the specific behaviour.

I see the need for Astronomy, but the reason I like these small specific packages which does one thing is because I can pick and choose what functionality I want and need and I keep my app size down. i.e. less bytes to send to my clients (speed/bandwidth cost).

Once we get a good lazy loading system for Meteor I would have no problem joining an effort as Astronomy because then you could use that suite and still only have the code you needed.

But until that time I've tried to talk with a couple of the guys doing "simple" collection packages like be to try and have an organization around our effort so that we work together more tightly. MeteorCommunity/discussions#72

The majority of Meteor developers won't be using this package directly but will instead use one of the pre-made behaviour packages instead and that was my intention from the beginning.

Also as a side note, this package was actually one of the first off shoots of @sewdn's package so I think a lot of the packages doing the same thing actually came after this.

The only reason for doing my own package was that I started out modifying one of his behaviours and ended up doing an almost complete rewrite of both the behaviour and the `base` functionality. So I ended up releasing my own package and after that I've actually been trying to get in touch with @sewdn to see if we couldn't combine out efforts but I've gotten no response.

**Comment by zimme** [comment]
So that's the back-story...

I see the use of a good comparison, but I think it's pretty clear from the README what the differences are.

However, do you have a good suggestion as to how I could add a comparison against some other packages without cluttering up the README all too much?

**Comment by dandv** [comment]
Thanks @zimme! Most informative.

As for a suggestion on adding a comparison without cluttering the README, probably the easiest would be to link to this issue.
