### ISSUE TITLE
New behaviour, orderable/sortable

### ISSUE THREAD

**Issue by mazing** [zimme/meteor-collection-behaviours#13]
An idea for another collection behaviour could be to add `order` fields. I know it's quite simple to add to relevant collections but it would be great to 'standardize' how they are added.

**Comment by zimme** [comment]
This is why I made this package only be a `base` package. So that you can add whatever behaviours you'd like.

If you need this fast, then I'd suggest you just create your own package which depends on this package and adds that kind of feature. and once I've tested it and seen that it does what it says, I'll add it to my list of Available behaviours.

Otherwise I'll try and see if I can't create a behaviour package for this after I've created `zimme:collection-archivable` package, which I haven't had time to do yet.

**Comment by zimme** [comment]
Would you have like a `Posts.changeOrder(...)` command too with this behaviour?

Could you maybe elaborate a bit on how you see this behaviour working?

**Comment by 57even** [comment]
Actually I just liked that I could remove createdAt, createdBy, updatedAt, updatedBy from most of my schemas after installing your packages, so I thought that next step would be to also remove `order` from most of them :-)

I'm not especially interested a changeOrder command since I use `Sortable` but I'm sure someone else will like it.

**Comment by zimme** [comment]
ok, but if you think of any good features for a `orderable`/`sortable` behaviour, then feel free to put it here.

**Comment by zimme** [comment]
Let's add these here. https://github.com/meteor-collectionbehaviours.
